docker_name: eduix/eduid-base
docker_tags:
    - "${GIT_LOCAL_BRANCH}"
builders:
  - docker
git:
  branch: master
  extensions:
    checkout_local_branch: true
triggers:
  cron: "@daily"
clean_workspace: true
downstream:
  - docker-eduid-base-staging
  - docker-eduid-base-stable

extra_jobs:
    - name: docker-eduid-base-staging
      builders:
        - docker
      docker_skip_tag_as_latest: true
      git:
        branch: staging
      downstream: []
    - name: docker-eduid-base-stable
      builders:
        - docker
      docker_skip_tag_as_latest: true
      git:
        branch: stable
      downstream: []
