docker_name: eduix/eduix-base
docker_tags:
    - "${GIT_LOCAL_BRANCH}"
triggers:
    cron: @daily
git:
    branches:
        - master
        - stable
    extensions:
        checkout_local_branch: true
clean_workspace: true
