docker_name: eduix/eduix-base
docker_tags:
    - "${GIT_LOCAL_BRANCH}"
git:
    branches:
        - master
        - stable
        - staging
    extensions:
        checkout_local_branch: true
clean_workspace: true

extra_jobs:
    - name: docker-eduix-base-daily
      builders:
        - docker
      docker_name: eduix/eduix-base
      triggers:
        github_push: false
        cron: @daily
