docker_name: eduix/eduix-base
builders:
  - script
script:
  - "echo \"Dummy job for starting branch specific ones\""
git:
  branches:
    - master
    - stable
    - staging
  extensions:
    checkout_local_branch: true
clean_workspace: true
downstream:
  - docker-eduix-base-master
  - docker-eduix-base-staging
  - docker-eduix-base-stable

extra_jobs:
    - name: docker-eduix-base-daily
      builders:
        - docker
      git:
        branch: master
        extensions:
            checkout_local_branch: true
      triggers:
        github_push: false
        cron: "@daily"
    - name: docker-eduix-base-master
      builders:
        - docker
      docker_tags:
        - "master"
      git:
        branch: master
    - name: docker-eduix-base-staging
      builders:
        - docker
      docker_tags:
        - "staging"
      git:
        branch: staging
    - name: docker-eduix-base-stable
      builders:
        - docker
      docker_tags:
        - "stable"
      git:
        branch: stable
